/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "acme",
  public: false,
  signature: "69a05a18ea68e1a17053305fc1f5cfb468c7dde7",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
