/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";

export interface EventWebhookValues {}

/**
 * Receives webhook events from Acme. Each event carries a `category` (deployments, security, or billing) that the integration flow routes on.
 *
 * @description Receives webhook events from Acme. Each event carries a `category` (deployments, security, or billing) that the integration flow routes on.
 * This object is used to support type hinting.
 */
export const eventWebhook = {
  key: "eventWebhook",
  perform: <TReturn>(_values: EventWebhookValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {},
} as const;

/**
 * Receives webhook events from Acme. Each event carries a `category` (deployments, security, or billing) that the integration flow routes on. Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const acmeEventWebhook = (values: {}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "acme",
        false,
        context.componentRegistry
      );
    },
    key: "eventWebhook",
    values,
  } as const;
};
