/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListEventsValues {
  /**
   * Connection
   *
   */
  connection: Connection;
}

/**
 * List Events
 *
 * @description List recent notification events reported by Acme.
 */
export const listEvents = {
  key: "listEvents",
  perform: async <TReturn>(values: ListEventsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.acme.listEvents({ ...values })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
