/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface AcmeApiKeyValues {
  /**
   * API Key
   *
   */
  apiKey: string;
}

/**
 * Acme API Key
 *
 * @comments Connect to the Acme API using an API key
 * This object is used to support type hinting.
 */
export const acmeApiKey = {
  key: "acmeApiKey",
  perform: (_values: AcmeApiKeyValues): Promise<void> => Promise.resolve(),
  inputs: {
    apiKey: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * Acme API Key Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const acmeAcmeApiKey = (
  stableKey: string,
  values: {
    apiKey: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  }
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "acme",
          false,
          context.componentRegistry
        );
      },
      key: "acmeApiKey",
      values,
    },
  });
};
